# -*- coding: utf-8 -*-
"""LPPS BTC-USD bubble indicator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0ohsd8ZZzVxrqG8q9XkAzi30l0yuX8F

# LPPLS Demo!

repo: https://github.com/Boulder-Investment-Technologies/lppls
"""

!pip install lppls yfinance

from lppls import lppls
import numpy as np
import pandas as pd
from datetime import datetime
import yfinance as yf

# yfinance ticker and time range
ticker_symbol = 'BTC-USD'  # NASDAQ Composite Index
start_date = '2015-01-01'
end_date = datetime.now().strftime('%Y-%m-%d')

# Fetch the data from Yahoo Finance
data = yf.download(ticker_symbol, start=start_date, end=end_date)

# Ensure the DataFrame has the necessary columns
data.reset_index(inplace=True)
# Check for the actual column name for Adjusted Close and replace 'Adj Close' if needed
# Possible alternatives: 'Close', 'Adjusted Close'
# Print data.columns to see the available columns
print(data.columns)
# If 'Adj Close' is not present, replace it with the correct column name below:
data = data[['Date', 'Close']] # Example: Replace 'Adj Close' with 'Close'

# Convert time to ordinal
time = data['Date'].apply(pd.Timestamp.toordinal).values

# Create list of observation data
price = np.log(data['Close']).values.reshape(-1) # Example: Replace 'Adj Close' with 'Close'

# Create observations array (expected format for LPPLS observations)
observations = np.array([time, price])

# Set the max number for searches to perform before giving-up
# The literature suggests 25
MAX_SEARCHES = 25

# Instantiate a new LPPLS model with the dataset
lppls_model = lppls.LPPLS(observations=observations)

# Fit the model to the data and get back the params
tc, m, w, a, b, c, c1, c2, O, D = lppls_model.fit(MAX_SEARCHES)

lppls_model.plot_fit()

res = lppls_model.mp_compute_nested_fits(
    workers=8,
    window_size=120,
    smallest_window_size=30,
    outer_increment=1,
    inner_increment=5,
    max_searches=25,
)

lppls_model.plot_confidence_indicators(res)